version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5121508
      POSTGRES_DB: catering_auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build:
      context: .
      dockerfile: docker/Dockerfile_migration
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=db user=postgres password=5121508 dbname=catering_auth_db port=5432 sslmode=disable" 

  auth_service:
    build:
      context: .
      dockerfile: docker/Dockerfile_service
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=db user=postgres password=5121508 dbname=catering_auth_db port=5432 sslmode=disable" 
    ports:
      - "8080:8080"



volumes:
  pgdata: