// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: valid_access_token.proto

package valid_access_token

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidAccessTokenService_ValidAccessToken_FullMethodName = "/auth.ValidAccessTokenService/ValidAccessToken"
)

// ValidAccessTokenServiceClient is the client API for ValidAccessTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidAccessTokenServiceClient interface {
	ValidAccessToken(ctx context.Context, in *ValidRequest, opts ...grpc.CallOption) (*ValidResponse, error)
}

type validAccessTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidAccessTokenServiceClient(cc grpc.ClientConnInterface) ValidAccessTokenServiceClient {
	return &validAccessTokenServiceClient{cc}
}

func (c *validAccessTokenServiceClient) ValidAccessToken(ctx context.Context, in *ValidRequest, opts ...grpc.CallOption) (*ValidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidResponse)
	err := c.cc.Invoke(ctx, ValidAccessTokenService_ValidAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidAccessTokenServiceServer is the server API for ValidAccessTokenService service.
// All implementations must embed UnimplementedValidAccessTokenServiceServer
// for forward compatibility.
type ValidAccessTokenServiceServer interface {
	ValidAccessToken(context.Context, *ValidRequest) (*ValidResponse, error)
	mustEmbedUnimplementedValidAccessTokenServiceServer()
}

// UnimplementedValidAccessTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidAccessTokenServiceServer struct{}

func (UnimplementedValidAccessTokenServiceServer) ValidAccessToken(context.Context, *ValidRequest) (*ValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidAccessToken not implemented")
}
func (UnimplementedValidAccessTokenServiceServer) mustEmbedUnimplementedValidAccessTokenServiceServer() {
}
func (UnimplementedValidAccessTokenServiceServer) testEmbeddedByValue() {}

// UnsafeValidAccessTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidAccessTokenServiceServer will
// result in compilation errors.
type UnsafeValidAccessTokenServiceServer interface {
	mustEmbedUnimplementedValidAccessTokenServiceServer()
}

func RegisterValidAccessTokenServiceServer(s grpc.ServiceRegistrar, srv ValidAccessTokenServiceServer) {
	// If the following call pancis, it indicates UnimplementedValidAccessTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidAccessTokenService_ServiceDesc, srv)
}

func _ValidAccessTokenService_ValidAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidAccessTokenServiceServer).ValidAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidAccessTokenService_ValidAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidAccessTokenServiceServer).ValidAccessToken(ctx, req.(*ValidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidAccessTokenService_ServiceDesc is the grpc.ServiceDesc for ValidAccessTokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidAccessTokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.ValidAccessTokenService",
	HandlerType: (*ValidAccessTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidAccessToken",
			Handler:    _ValidAccessTokenService_ValidAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "valid_access_token.proto",
}
