// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: valid_access_token.proto

package valid_access_token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidRequest) Reset() {
	*x = ValidRequest{}
	mi := &file_valid_access_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidRequest) ProtoMessage() {}

func (x *ValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valid_access_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidRequest.ProtoReflect.Descriptor instead.
func (*ValidRequest) Descriptor() ([]byte, []int) {
	return file_valid_access_token_proto_rawDescGZIP(), []int{0}
}

func (x *ValidRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidResponse) Reset() {
	*x = ValidResponse{}
	mi := &file_valid_access_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidResponse) ProtoMessage() {}

func (x *ValidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valid_access_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidResponse.ProtoReflect.Descriptor instead.
func (*ValidResponse) Descriptor() ([]byte, []int) {
	return file_valid_access_token_proto_rawDescGZIP(), []int{1}
}

func (x *ValidResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_valid_access_token_proto protoreflect.FileDescriptor

const file_valid_access_token_proto_rawDesc = "" +
	"\n" +
	"\x18valid_access_token.proto\x12\x04auth\"0\n" +
	"\fValidRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"G\n" +
	"\rValidResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2V\n" +
	"\x17ValidAccessTokenService\x12;\n" +
	"\x10ValidAccessToken\x12\x12.auth.ValidRequest\x1a\x13.auth.ValidResponseB\x15Z\x13/valid_access_tokenb\x06proto3"

var (
	file_valid_access_token_proto_rawDescOnce sync.Once
	file_valid_access_token_proto_rawDescData []byte
)

func file_valid_access_token_proto_rawDescGZIP() []byte {
	file_valid_access_token_proto_rawDescOnce.Do(func() {
		file_valid_access_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valid_access_token_proto_rawDesc), len(file_valid_access_token_proto_rawDesc)))
	})
	return file_valid_access_token_proto_rawDescData
}

var file_valid_access_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_valid_access_token_proto_goTypes = []any{
	(*ValidRequest)(nil),  // 0: auth.ValidRequest
	(*ValidResponse)(nil), // 1: auth.ValidResponse
}
var file_valid_access_token_proto_depIdxs = []int32{
	0, // 0: auth.ValidAccessTokenService.ValidAccessToken:input_type -> auth.ValidRequest
	1, // 1: auth.ValidAccessTokenService.ValidAccessToken:output_type -> auth.ValidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_valid_access_token_proto_init() }
func file_valid_access_token_proto_init() {
	if File_valid_access_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valid_access_token_proto_rawDesc), len(file_valid_access_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_valid_access_token_proto_goTypes,
		DependencyIndexes: file_valid_access_token_proto_depIdxs,
		MessageInfos:      file_valid_access_token_proto_msgTypes,
	}.Build()
	File_valid_access_token_proto = out.File
	file_valid_access_token_proto_goTypes = nil
	file_valid_access_token_proto_depIdxs = nil
}
