/*
 * Catering service
 *
 * Auth service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	routespkg "github.com/GIT_USER_ID/GIT_REPO_ID/internal/routes"
)

func main() {
	routes := routespkg.ApiHandleFunctions{}

	log.Printf("Server started")

	router := routespkg.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
