/*
 * Catering service
 *
 * Auth service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginPost200Response struct {

	AccessToken string `json:"accessToken,omitempty"`
}
