/*
 * Catering service
 *
 * Auth service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RegisterPostRequest struct {

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Email string `json:"email,omitempty"`
}
