/*
 * Catering service
 *
 * Auth service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RefreshTokenPostRequest struct {

	RefreshToken string `json:"refreshToken,omitempty"`
}
